### ISSUE TITLE
Error in plotRP

### ISSUE THREAD

**Issue by istallworthy** [morenococo/crqa#2] opened 2023-10-16 20:13 UTC
Hello, 

I am consistently encountering the following error when i try to run `plotRP() `with the `RP` output from either `crqa()` or `mdcrqa()`, and i'm wondering if you are aware of why this might be happening? 

<img width="716" alt="Screen Shot 2023-10-16 at 4 11 05 PM" src="https://github.com/morenococo/crqa/assets/31548151/afab0ffd-2a52-408f-8dad-768d8f3093d3">

Thanks in advance,
Isa

**Comment by morenococo** [comment] 2023-10-17 07:37
Hi @istallworthy , thanks for flagging this up! 
I had to perform some maintenance to crqa() to comply with updates on CRAN and maybe something went wrong with this function. I am assuming that you have installed the latest version crqa.2.0.4

@a-paxton, if you have time,  do you mind having a look at the function? I had to rewrite parts of it because the version you proposed did not pass the CRAN check, especially the initialization of parameters, and consequently reshuffled part of it. 
I am sure the issue is there ...
Otherwise, let me know, and I will have a look at it. 
Many thanks!

**Comment by istallworthy** [comment] 2023-10-17 12:54
Thank you, @morenococo and @a-paxton. I do have the latest crqa installed.

**Comment by a-paxton** [comment] 2023-10-19 13:14
Thanks for flagging this! I'll take a look as soon as I can, at least in the next few days.

**Comment by a-paxton** [comment] 2023-11-03 18:26
Hi, @istallworthy! Apologies for my very late reply on this. (Conference season is approaching!) I'm not sure exactly why it threw that specific error, but I'm hoping my edited code will help with it.

**Comment by morenococo** [comment] 2024-07-11 07:34
This issue was already fixed in a previous version. We have now changed the function entirely and replaced it with plot_rp, which is faster and relies on ggplot2, making it more customizable

**Closed by morenococo** 2024-07-11 07:34 UTC
Labels: bug
